redforce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('rforce.urls','rfl'), namespace='rfl')),
    
]

rforce/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='loginpage'),
    path('home/', views.home, name='homepage'),
    path('upload/', views.upload, name='upload'),
    path('setUpProfile/', views.setUpProfile, name='setUpProfile'),
    path('faceRecog/', views.faceRecog, name='faceRecog'),
    path('check/', views.check, name='check'),
    #path('face_recog', views.faceRecog, name='face_recog'),
    path('logout/', views.logout, name='logout'),
    path('uploadfile/', views.uploadfile, name='uploadfile'),
    path('viewfile/', views.viewfile, name='viewfile'),
    path('openfile/<id>/', views.openfile, name='openfile'),
    path('deletefile/<id>/', views.deletefile, name='deletefile'),
]

rforce/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True, unique=True)
    img= models.TextField(unique=True,null=False)
    key =models.CharField(max_length=100, null=True)
    
class TestUser(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    img= models.TextField(unique=True,null=False)

rforce/views.py
from distutils.command import build
from importlib.metadata import files
import io
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse
from googleapiclient.http import MediaIoBaseDownload
import sys
import cv2
from django.template import RequestContext
from .models import UserInfo, TestUser
import face_recognition
import base64
import os
from django.shortcuts import redirect
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render
from rforce import models
import requests
import json
import google.auth
from google.oauth2.credentials import Credentials
from apiclient import errors
from django.contrib import messages
import os.path
from allauth.socialaccount.models import SocialAccount, SocialApp


import docx2txt
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.models import SocialAccount, SocialApp
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from googleapiclient.http import MediaFileUpload
from allauth.socialaccount.models import SocialApp
from googleapiclient.errors import HttpError
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.http import MediaFileUpload
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from django.core.files.storage import FileSystemStorage
from cryptography.fernet import Fernet

count = 0
stop = 0
anti="pika"
face_flag=0


from allauth.socialaccount.models import SocialAccount, SocialApp
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from googleapiclient.http import MediaFileUpload
from allauth.socialaccount.models import SocialToken, SocialApp
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseDownload
import io
import os
import docx2txt

# Create your views here.
def login(request):
    auth_logout(request)
    return render(request,'index.html')

def home(request):
    folder_flag=0
    app_google = SocialApp.objects.get(provider="google")
    account = SocialAccount.objects.get(user=request.user)
    user_tokens = account.socialtoken_set.first()
    creds = Credentials(
    token=user_tokens.token,
    refresh_token=user_tokens.token_secret,
    client_id=app_google.client_id,
    client_secret=app_google.secret,
                    )
    service = build('drive', 'v3', credentials=creds)
    page_token = None
    response = service.files().list(q="mimeType='application/vnd.google-apps.folder'",
                                            spaces='drive',
                                            fields='nextPageToken, '
                                                   'files(id, name)',
                                            pageToken=page_token).execute()
    for file in response.get('files', []):
        print(type({file.get("name")}))
        print(str({file.get("name")}))    
        if(str({file.get("name")})=="{'Redforce'}"):
            folder_flag=1
            break
    if(folder_flag==0):
          
        folder = 'Redforce'
                
        file_metadata = {
                'name': folder,
                'mimeType': 'application/vnd.google-apps.folder'
            }
                
        service.files().create(body=file_metadata).execute()
    return render(request,'home.html')

def upload(request):
    try:
        global face_flag
        print("face-flag in upload",face_flag)
        if face_flag!=1:
            face_flag=1
            return redirect(f"/faceRecog/")
        
        if request.method=="POST":
            face_flag=0
            app_google = SocialApp.objects.get(provider="google")
            account = SocialAccount.objects.get(user=request.user)
            user_tokens = account.socialtoken_set.first()
            creds = Credentials(
            token=user_tokens.token,
            refresh_token=user_tokens.token_secret,
            client_id=app_google.client_id,
            client_secret=app_google.secret,
                            )
            service = build('drive', 'v3', credentials=creds)
            
            results = service.files().list(
                pageSize=10, fields="nextPageToken, files(id, name)").execute()
            items = results.get('files', [])
            folder_id=""
            for item in items:
                if item['name']=="Redforce":
                    folder_id=item['id']
                    
            fname=request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(fname.name, fname)
            uploaded_file_path = fs.path(filename)
            tname= fname.name
            Object=UserInfo.objects.get(user=request.user)
            ftool = Fernet(Object.key)
            
            data=''
            with open(uploaded_file_path,'rb') as reader:
                data=reader.read()
            print(data)
            
            encryptedData=ftool.encrypt(data)
            
            with open(uploaded_file_path,'wb') as writer:
                writer.write(encryptedData)
                writer.close()
            file_metadata={
                'name': tname,
                'parents' : [folder_id],
            }
            mime_Type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            media = MediaFileUpload(uploaded_file_path,mimetype=mime_Type)
            service.files().create(
                body=file_metadata,
                media_body=media,
            ).execute() 
            return redirect(f"/home/")  
        return render(request,'upload.html')
    except:
        face_flag=0
        messages.info(request, 'Cannot Upload Empty File')
        return render(request,'home.html')



def setUpProfile(request):
    global stop
    if (stop==1):
        return redirect(f"/faceRecog/")
    user = request.user
    print(user)
    alluser =  models.UserInfo.objects.filter()
    print(alluser)
    list = []
    list.append(alluser)
    
    for i in alluser:
        if(user==i.user):
            return redirect(f"/faceRecog/")        
        
    if request.method=="POST":
        user=UserInfo.objects.create(
        img=request.POST.get("img_data"),
        user = request.user,
        key = Fernet.generate_key().decode()
        
        )
        stop = 1
        return redirect(f"/faceRecog/")
      
    return render(request,'setUpProfile.html')

def faceRecog(request):
    if request.method=="POST":
        test=TestUser.objects.create(
        img=request.POST.get("img_data"),
        user = request.user
        )
        global anti 
        anti= request.POST.get("img_data2")
        print(anti)
        global stop
        stop=0   
    
        return redirect(f"/check/")
    return render(request,'faceRecog.html')


def check(request):
    #temp = flag
    global face_flag
    db = UserInfo.objects.get(user=request.user)
    db_img=db.img
    dbu=db.user
    
    
    db1 = TestUser.objects.get(user=request.user)
    db_img1=db1.img
    dbu1=db1.user
    
    
    with open(f"{dbu}.jpg", "wb") as fh:
        fh.write(base64.b64decode(db_img))
    
    try:       
        known_image = face_recognition.load_image_file(f"{dbu}.jpg")
        known_encoding = face_recognition.face_encodings(known_image)[0]
         
        # #Anti-spoofing starts here

        url = "https://liveness-detection1.p.rapidapi.com/api/v1/liveness-detection"

        payload = {
            "imageUrl":anti,
            "isface": True
        }
        headers = {
            "content-type": "application/json",
            "X-RapidAPI-Key": "3edf7b5a71mshb18cb7601af0b1bp15d53ajsnbf3ed97aac62",
            "X-RapidAPI-Host": "liveness-detection1.p.rapidapi.com"
        }

        response = requests.request("POST", url, json=payload, headers=headers)
        data = response.json()
        print(type(data))
        keys = data.keys()
        print(keys)
        print(type(data['predict']))

        print(response.text)
        #Anti-Spoofing ends here
        with open(f"{dbu1}.jpg", "wb") as fk:
            fk.write(base64.b64decode(db_img1))
        unknown_image = face_recognition.load_image_file(f"{dbu1}.jpg")

        
        unknown_encoding = face_recognition.face_encodings(unknown_image)[0]
        
        results = face_recognition.compare_faces([known_encoding], unknown_encoding,tolerance=0.45)
        print(results)

        f = open(f"{dbu}.jpg", 'w')
        f.close()
        os.remove(f.name)
        
        f1 = open(f"{dbu1}.jpg", 'w')
        f1.close()
        os.remove(f1.name)

        #removing test-user
        instance =TestUser.objects.get(user=request.user)
        instance.delete()
        stresult = str(results)
        global count
        
        if (stresult == "[True]" and data['predict']=="real"):
            if face_flag==0:
                return redirect(f"/home/")
            elif face_flag==1:
                return redirect(f"/upload/")
            elif face_flag==2:
                return redirect(f"/viewfile/")         
        else:
            count=count+1
            print(count)
            if(count==3):
                count = 0
                return redirect(f"/logout/")
            else:
                return redirect(f"/faceRecog/")
    except:
        #global count2
        count=count+1
        
        print("An exception occurred")   
        f1 = open(f"{dbu1}.jpg", 'w')
        f1.close()

rforce/templates/antispoof.html
<!DOCTYPE html>

  <head>
    <title>Face Anti-Spoof | Red Force</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" >
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'faceRecog.css' %}">
  
  </head>
  <body>
    <section>
      <div class="bg-light">
        {% if user.is_authenticated %}
          <div class="container d-flex justify-content-between p-2">
            <a class="navbar-brand" href="#">
              <img src="{% static 'images/RedForce_transparent.png' %}" width="70px" height="55px" alt="" class="d-inline-block align-text-top">
            </a>
            <div class="d-grid gap-2 d-md-flex">
              
              <div class="topbar d-md-flex">
                <a class="text-light" href="{% url 'rfl:logout' %}"><p>Logout</p></a>
              </div>  
            </div>
          </div>
        <!---->
    </section>
    <section>
        <div class="banner" style="padding: 0px 0px;">
            <br>
            <h3>Face Anti-Spoof</h3>
            <video id="first" muted></video> 
            <button class="btn btn-success" onclick="startCapture()">Play</button>
            <button class="btn btn-danger" onclick="stopCapture()">Stop</button>
            <video id="second" controls></video> 
        </div>

        
    </section>
    <script>
        let video=document.getElementById('first');
        let mediaRecorder=null;
        navigator.mediaDevices.getUserMedia({video:true, audio:true})
        .then(function(stream){
            video.scrObject = stream;
            video.play();

            mediaRecorder=new MediaRecorder(stream, {mimeType:"video/webm"});
            mediaRecorder.ondataavailable= function(event){
                if(event.data.size>0){
                    const reader = new window.FileReader();
                    reader.readAsDataURL(event.data);
                    reader.onloadend=function(){
                        let base64=reader.result.split('base64,')[1];
                        let recording =document.getElementById('second');
                        recording.src="data:video/webm;base64"+base64;
                        recording.type="video/webm";
                        recording.play();
                    }
                }
            }
        }
        )
        function startCapture(){
            mediaRecorder.start();
        }
        function stopCapture(){
            mediaRecorder.stop();
        }

    </script>
    {% else %}
    <div class="warning" style="text-align: center;">
      <img src="{% static 'images/warning sign.jpg' %}" alt="">
      <h1>Permission denied!</h1>
      <h4>You might not be logged in</h4>
    </div>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

rforce/templates/fileviewer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Files</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" >
    
    <link rel="stylesheet" href="{% static 'fileviewer.css' %}">
</head>
<body>
    <header>
        <div class="top-content">
          {% if user.is_authenticated %}
          <div class="container d-flex justify-content-between p-2">
            <!--<a class="navbar-brand" href="#">
              <img src="{% static 'images/transparent_logo.png' %}" width="105px" height="50px" alt="" class="d-inline-block align-text-top">
            </a>-->
            <div class="d-grid gap-2 d-md-flex">
              <div class="topbar d-md-flex">
                <a class="text-light" href="{% url 'rfl:viewfile' %}"><p>Go Back</p></a>
              </div>
              <div class="topbar d-md-flex">
                <a class="text-light" href="{% url 'rfl:logout' %}" style="padding-left: 20px;"><p>Logout</p></a>
              </div>  
            </div>
          {% endif %}
        </div>
    </header>
    <div class="content">
      <div>
          {% if object_list %}
          {% for obj in object_list %}
          {{obj}}
          <br>
          {% endfor %}
          {% endif %}
      </div>
  </div>
</body>
</html>

rforce/templates/home.html
<!DOCTYPE html>

  <head>
    <title>Home | Red Force</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" >
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'home.css' %}">
  
  </head>
  <body>
    
  
        <!--  
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>-->
        

    <section>
      <div class="bg-light">
        {% if user.is_authenticated %}
          <div class="container d-flex justify-content-between p-2">
            <a class="navbar-brand" href="#">
              <img src="{% static 'images/RedForce_transparent.png' %}" width="70px" height="55px" alt="" class="d-inline-block align-text-top">
            </a>
            <div class="d-grid gap-2 d-md-flex">
              
              <div class="topbar d-md-flex">
                <a class="text-light" href="{% url 'rfl:logout' %}"><p>Logout</p></a>
              </div>  
            </div>
          </div>
        {%endif%}
    </section>
    <!--<ul class="messages">
      {% for message in messages %}
        <div class="alert alert-dismissible alert-success">
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          
        </div>
     {% endfor %} </ul>-->
     <section class="container text-center" style="display: flex; margin-top: 60px; ">
      <div class="col-6">
        <a href="{% url 'rfl:upload'%}"><div class="card" style="width: 18rem; margin: auto;">
          <div class="card-body">
            <h5>Upload files on <br> Google Drive</h5></div>
        </div></a>
      </div>
      <div class="col-6">
        <a href="{% url 'rfl:viewfile'%}"><div class="card" style="width: 18rem; margin: auto;">
          <div class="card-body">
            <h5>View files on <br> Google Drive</h5></div>
        </div></a>
      </div>

     </section>
     
      
     
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

rforce/templates/index.html
<!DOCTYPE html>
{% load socialaccount %}

  <head>
    <title>Dashboard | Red Force</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" >
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'style.css' %}">
  
  </head>
  <body>
    
    {% block body %}
    <section class="content">
      <div class="box text-center" >
        <img src="{% static 'images/RedForce_transparent.png' %}" width="220px">
        <h1>Welcome to <span>RedForce</span></h1>  
        <h4>Safety is our #1 priority</h4>
        <div class="google" >
          <h4>Login to your account <br> with Google</h4>
          <a title="Google" class="" href="/accounts/google/login/">
            <!--<a href="{% provider_login_url "google" %}">-->
            <img src="{% static 'images/google_logo.png' %}" width="18px">
            Join with Google
          </a>
        </div>
    </div>
  </section> 
    <div class="bg-dark">
      {% if user.is_authenticated %}
      <div class="container d-flex justify-content-between ">
        
      
      {% endif %}
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

rforce/templates/upload.html
<!DOCTYPE html>

  <head>
    <title>Home | Red Force</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" >
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'home.css' %}">
  
  </head>
  <body>
    
  
        <!--  
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>-->
        
    
    <section>
      <div class="bg-light">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if user.is_authenticated %}
          <div class="container d-flex justify-content-between p-2">
            <a class="navbar-brand" href="#">
              <img src="{% static 'images/RedForce_transparent.png' %}" width="70px" height="55px" alt="" class="d-inline-block align-text-top">
            </a>
            <div class="d-grid gap-2 d-md-flex">
              <div class="topbar d-md-flex">
                <a class="text-light" href="{% url 'rfl:homepage' %}"><p>Go Back</p></a>
              </div> 
              <div class="topbar d-md-flex" style="padding-left: 20px;">
                <a class="text-light" href="{% url 'rfl:logout' %}"><p>Logout</p></a>
              </div>  
            </div>
          </div>
        
    </section>
    <!--<ul class="messages">
      {% for message in messages %}
        <div class="alert alert-dismissible alert-success">
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          
        </div>
     {% endfor %} </ul>-->
    <section>
      
      <form method="POST" action ="{% url 'rfl:upload' %}" enctype="multipart/form-data" style="margin: 40px 40px;">
        {% csrf_token %}
        <label for="myfile">Select a file:</label>
        <input type="file" id="myfile" name="myfile"><br><br>
        <input type="submit"  name="upfile1" id="myfile1">
        <br> <br>
      </form>
    </section>
    {% else %}
    <div class="warning" style="text-align: center;">
      <img src="{% static 'images/warning sign.jpg' %}" alt="">
      <h1>Permission denied!</h1>
      <h4>You might not be logged in</h4>
    </div>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

rforce/templates/viewfiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Files</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" >
    
    <link rel="stylesheet" href="{% static 'viewfile.css' %}">
</head>
<body>
  <section>
    <div class="bg-light">
      {% if user.is_authenticated %}
        <div class="container d-flex justify-content-between p-2">
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/RedForce_transparent.png' %}" width="70px" height="55px" alt="" class="d-inline-block align-text-top">
          </a>
          <div class="d-grid gap-2 d-md-flex">
            <div class="topbar d-md-flex">
              <a class="text-light" href="{% url 'rfl:homepage' %}"><p>Go Back</p></a>
            </div> 
            <div class="topbar d-md-flex" style="padding-left: 20px;">
              <a class="text-light" href="{% url 'rfl:logout' %}"><p>Logout</p></a>
            </div>  
          </div>
        </div>
      {%endif%}
  </section>
    <section>
        <div class="container">
            
            <div class="row p-5 text-center">
                <h2 style="text-align: center; margin-bottom: 20px;">List of files</h2>
                {% for name,id in object_list %}
                
                <div class="col-4">
                    <div class="card bg-dark p-4" style="width: 75%; margin: auto; margin-bottom: 25px;">  
                      <div class="card-body">
                          <div style="padding-bottom: 20px;">
                            <h5 class="card-title">{{name}}</h5>
                          </div>
                          <div class="twobtns">
                            <div class="buttons">
                              <a href="{% url 'rfl:openfile' id%}" class="btn btn-primary" style="margin-right: 5px;">Open</a>
                            </div>
                            <div class="buttons">
                              <a href="{% url 'rfl:deletefile' id%}" class="btn btn-danger" style="margin-right: 5px;">Delete</a>
                            </div>
                          </div>
                          
                          
                        </div>
                    </div>
                </div>
                {%endfor%}

            
        </div>
    </section>
</body>
</html>